-- Activity7

SELECT SUM(PURCHASE_AMOUNT) AS TOTAL FROM orders;
SELECT AVG(PURCHASE_AMOUNT) AS AVERAGE FROM orders;
SELECT MAX(PURCHASE_AMOUNT) AS MAXIMUM FROM orders;
SELECT MIN(PURCHASE_AMOUNT) AS minimum FROM orders;
SELECT COUNT(DISTINCT salesman_id) AS TOTALCOUNT FROM orders;